config/routes.rb
Mameblog::Application.routes.draw do

  resources :hashtag, only: [:show]

  resources :password_resets, only: [:new, :create, :update, :edit]

  resources :brothers, except: [:destroy] do
    member do
      get :following
      get :followers
    end
  end
  get '/discover', to: 'brothers#discover'

  resources :sessions, only: [:create, :destroy]
  resources :entries, only: [:create, :destroy, :show, :update, :edit] do
    resources :beans, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  root 'timelines#index'

  get '/timelines/brothers', to: 'timelines#brothers'
  get '/signup',  to: 'brothers#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get "/contributors", to: 'contributors#index'
  get "/jinja", to: 'jinja#index'
  get "/jinja/omikuji", to: 'jinja/omikuji#index'
  get "/jinja/osaisen", to: 'jinja/osaisen#index'

  get 'tent/home', to: 'tent/home#index'

  get '/:name', to: 'brothers#show', as: 'brothers_name'
  get '/:name/feed', to: 'brothers#rss', defaults: { format: :rss }
  get '/:name/following', to: 'brothers#following', as: 'following'
  get '/:name/followers', to: 'brothers#followers', as: 'followers'
end

app/views/shared/_ad.html.haml
- unless signed_in?
  = link_to signup_path, class: 'ad', onclick: "ga('send', 'event', 'ad_welcome', 'click');" do
    %span<>
      はじめまして。#{myself.sample}は日本の豊かなブログサービスです。
    %br.view-desktop<>
    %span<
      ブラザーに
    %u
      今すぐなる

app/views/shared/_email_nil_brother_notice.html.haml
- if current_brother.email.blank?
  = link_to '設定ページでメールアドレスを設定する', edit_brother_path(current_brother)

app/views/shared/_entries.html.haml
%div#content{data: {max: {page: @entries.total_pages}}}
  %article#entries.autopager-content
    - @entries.each do |entry|
      %section.entry.autopager-item{data: {beans: {count: entry.beans.count}}}
        %h1.entry-title= link_to entry.title, entry
        %div.entry-content
          = sanitize_markdown convert_bro(entry.content_as_markdown)
          - if signed_in? && !current_brother?(entry.brother)
            = form_tag entry_beans_path(entry), remote: true, class: 'entry-beans is_throwable', method: 'post', name: 'beans_name' do
              %span.beans-count<>
                = entry.beans.count
          - elsif 0 < entry.beans.count
            %div.entry-beans
              %span.beans-count<>
                = entry.beans.count
  .page-load-status
    .infinite-scroll-request
      = image_tag 'loading.gif', alt: 'Loading...'
= paginate @entries

app/views/shared/_entry_form.html.haml
%div.editor
  %div.editor-wrapper
    %div.editor-content
      %div.page
        = form_for(current_brother.entries.build) do |f|
          = render 'shared/error_messages', object: f.object
          %div#entry_form.field
            = f.text_field :title, id: 'entry-form-title', class: 'input input-text', placeholder: "!!! タイトル !!!"
            = f.text_area :content, id: 'entry-form-content', class: 'input input-textarea', rows: '4', placeholder: "!!! 本文 !!!"
            = f.submit "!!! 投稿 !!!", data: { disable_with: "!!! 投稿中 !!!" }, id: 'entry-form-submit', class: "button button-horizontal button-primary"
      %nav.nav-close
        %i.iconbutton.nav-editor-control<>
          &#10060;

app/views/shared/_entry_update_form.html.haml
= form_for(@entry) do |f|
  = render 'shared/error_messages', object: f.object
  %div#entry_form.field
    = f.text_field :title, id: 'entry-form-title', class: 'input input-text', placeholder: "!!! タイトル !!!"
    = f.text_area :content, id: 'entry-form-content', class: 'input input-textarea', rows: '4', placeholder: "!!! 本文 !!!"
    = f.submit "!!! 編集 !!!", data: { disable_with: "!!! 投稿中 !!!" }, id: 'entry-form-submit', class: "button button-horizontal button-primary"

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div.alert.alert-error
    = pluralize(object.errors.count, "error")
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_profile.html.haml
%div.profile
  %h1.profile-name
    = @brother.name[0,1].upcase + '.'
  %ul.stats
    %li.stats-list
      %a.stats-content{href: "/brothers/#{@brother.name}"}
        %span.stats-label
          日記
        %span.stats-number
          #{@brother.entries.count}
          %span.stats-beans<>
            %i.icon<>
              &#63235;
            %span<>
              #{@beans.count}
    %li.stats-list
      %a.stats-content{href: "#{following_brother_path(@brother)}"}
        %span.stats-label
          兄弟
        %span.stats-number
          = @brother.followed_brothers.count + 1
    %li.stats-list
      %a.stats-content{href: "#{followers_brother_path(@brother)}"}
        %span.stats-label
          保護者
        %span.stats-number
          = @brother.followers.count

app/views/shared/_session_header.html.haml
%header.session-header
  = image_tag 'brand/brand-white.svg', class: 'brand', alt: 'まめぶろ'

app/views/shared/_stats.html.haml
- @brother ||= current_brother
%div.stats
  %a.stat.entries-number{href: "/#{@brother.name}"}
    %span.separate-border
      %span.number
        = @brother.entries.count
      %span.label
        日記
  %a.stat.following{href: "#{following_path(@brother)}"}
    %span.separate-border
      %span.number
        = @brother.followed_brothers.count + 1
      %span.label
        人兄弟
  %a.stat.follower{href: "#{followers_path(@brother)}"}
    %span.separate-border
      %span.number
        = @brother.followers.count
      %span.label
        保護者
  %span.stat.beans-count
    %span.number
      = @beans.count
    %span.label
      まめ

app/views/shared/_tips.html.haml
%div.entry.entry-pr.nav-editor-control.autopager-item
  #{tips.sample}