config/routes.rb
Mameblog::Application.routes.draw do

  resources :hashtag, only: [:show]

  resources :password_resets, only: [:new, :create, :update, :edit]

  resources :brothers, except: [:destroy] do
    member do
      get :following
      get :followers
    end
  end
  get '/discover', to: 'brothers#discover'

  resources :sessions, only: [:create, :destroy]
  resources :entries, only: [:create, :destroy, :show, :update, :edit] do
    resources :beans, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  root 'timelines#index'

  get '/timelines/brothers', to: 'timelines#brothers'
  get '/signup',  to: 'brothers#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get "/contributors", to: 'contributors#index'
  get "/jinja", to: 'jinja#index'
  get "/jinja/omikuji", to: 'jinja/omikuji#index'
  get "/jinja/osaisen", to: 'jinja/osaisen#index'

  get 'tent/home', to: 'tent/home#index'

  get '/:name', to: 'brothers#show', as: 'brothers_name'
  get '/:name/feed', to: 'brothers#rss', defaults: { format: :rss }
  get '/:name/following', to: 'brothers#following', as: 'following'
  get '/:name/followers', to: 'brothers#followers', as: 'followers'
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    if signed_in?
      followed_ids = []
      Relationship.where(follower_id: current_brother.id).each do |rel|
        followed_ids << rel.followed_id
      end
      @entries = Entry.where(brother_id: followed_ids).page params[:page]
    else
      @entries = Entry.page params[:page]
    end
  end

  def brothers
    if signed_in?
      @entries = Entry.where.not(brother_id: current_brother.id).page params[:page]
    else
      redirect_to root_path
    end
  end
end

app/views/timelines/_navs.html.haml
%nav.nav-pills
  %ul{class: "nav-pill-wrapper current-#{current_page}"}
    %li.nav-pill.nav-pill-timelines-index
      = link_to root_path do
        兄弟
    %li.nav-pill.nav-pill-timelines-brothers
      = link_to timelines_brothers_path do
        ブラザー

app/views/timelines/brothers.html.haml
- if signed_in?
  = render 'navs', current_page: 'timelines-brothers'
= render 'shared/ad'
= render 'shared/entries'

app/views/timelines/index.html.haml
- if signed_in?
  = render 'navs', current_page: 'timelines-index'
= render 'shared/ad'
= render 'shared/entries'